### ISSUE TITLE
OrgPolicy v2 module forcing Google provider version to be < 5.0

### ISSUE THREAD

**Issue by sanspace** [terraform-google-modules/terraform-google-org-policy#110]
https://github.com/terraform-google-modules/terraform-google-org-policy/blob/7e71185bfd56e683706d4b0e0d69ba36250029dc/modules/org_policy_v2/versions.tf#L23

Because of the above hard-coded version requirement, the latest Google provider (v5.1.0) cannot be used. If there's no specific reason for this module to use the Google provider <5.0, let's please modify or remove this constraint. Thank yoU!

**Comment by gustaff-weldon** [comment]
@sanspace it depends on https://github.com/terraform-google-modules/terraform-google-org-policy/pull/105 now :)
