### ISSUE TITLE
Invalid syntax, when enforce variable is default (empty string)

### ISSUE THREAD

**Issue by ivankorn** [terraform-google-modules/terraform-google-org-policy#12]
The logic assumes var.enforce to be one of
- true
- false
- "" [(default)](https://github.com/terraform-google-modules/terraform-google-org-policy/blob/master/variables.tf#L34)

But we can't use `not` operator with empty string.

Offending lines:
- [enforced = "${!var.enforce}"](https://github.com/terraform-google-modules/terraform-google-org-policy/blob/master/boolean_constraints.tf#L69)
- [enforced = "${!var.enforce}"](https://github.com/terraform-google-modules/terraform-google-org-policy/blob/master/boolean_constraints.tf#L55)

```
[16:09][user@host:~]$ /home/data/Soft/terraform_11/terraform -v
Terraform v0.11.14

Your version of Terraform is out of date! The latest version
is 0.12.5. You can update by downloading from www.terraform.io/downloads.html
[16:09][mulder@my:~]$ /home/data/Soft/terraform_11/terraform console
> ! ""
__builtin_StringToBool: strconv.ParseBool: parsing "": invalid syntax in:

${! ""}
> ! true
false
> ! false
true
>  
```

This bug is not covered by tests or examples, however it's likely fixed (to be confirmed!) in [TF 0.12 PR](https://github.com/terraform-google-modules/terraform-google-org-policy/pull/11)

**Comment by morgante** [comment]
Technically the `""` value is supposed to be acceptable. Specifically, for list values you can set `enforce` to `""` and provide `allow` and `deny` values directly. This is explained here: https://github.com/terraform-google-modules/terraform-google-org-policy#variables

Is this current behavior failing?

**Comment by ivankorn** [comment]
> Technically the `""` value is supposed to be acceptable. Specifically, for list values you can set `enforce` to `""` and provide `allow` and `deny` values directly. This is explained here: https://github.com/terraform-google-modules/terraform-google-org-policy#variables
> 
> Is this current behavior failing?

It should fail as it introduces syntax error in two lines I highlighted in the issue description.
- [enforced = "${!var.enforce}"](https://github.com/terraform-google-modules/terraform-google-org-policy/blob/master/boolean_constraints.tf#L69)
- [enforced = "${!var.enforce}"](https://github.com/terraform-google-modules/terraform-google-org-policy/blob/master/boolean_constraints.tf#L55)

However nobody noticed that as tests and examples don't provide coverage for this specific cases (when we have `exclude folders` or `exclude projects` set and `enforce` defaulted to "" )

If we try to come-up with an example evaluation of `"${!var.enforce}"` should rise `syntax error`

**Comment by bohdanyurov-gl** [comment]
@morgante We've agreed to replace"" with "null" to change "var.enforce" type to bool (that makes sense with TF0.12)
So nothing has changed here. This issue is related to the fact that this bug is present on master right now

**Comment by morgante** [comment]
I want to be very clear about how this is meant to work.

For boolean constraints, a value *must* be provided for `var.enforce`. We can and should add guardrails to make sure that is true.

For *list* constraints, as the document I linked explains:
> List policies (with policy_type: "list") can set one of the following variables. Only one may be set.
enforce: if "true" policy will deny all, if "false" policy will allow all (default true)
allow: list of values to include in the policy with ALLOW behavior
deny: list of values to include in the policy with DENY behavior

This is implemented in this file: https://github.com/terraform-google-modules/terraform-google-org-policy/blob/master/list_constraints.tf#L21

Please confirm this existing behavior will not change in any fixes you make.

**Comment by ivankorn** [comment]
@morgante
There are previously written test for `list constraints` with `enforce` set with `false`:
- [template](https://github.com/ivankorn/terraform-google-org-policy/blob/7/test/integration/list_constraints/launch.sh#L119) --> [check](https://github.com/ivankorn/terraform-google-org-policy/blob/7/test/integration/list_constraints/integration.bats#L56) --> sort of "enforce false --> allow all"

And for `list constraints` with `enforce` set with `true`:
- [template](https://github.com/ivankorn/terraform-google-org-policy/blob/7/test/integration/list_constraints/launch.sh#L110) --> [check](https://github.com/ivankorn/terraform-google-org-policy/blob/7/test/integration/list_constraints/integration.bats#L47) --> sort of "enforce true --> deny all"

As well as `deny` and `allow` ones:
- [template](https://github.com/ivankorn/terraform-google-org-policy/blob/7/test/integration/list_constraints/launch.sh#L133) --> [check](https://github.com/ivankorn/terraform-google-org-policy/blob/7/test/integration/list_constraints/integration.bats#L75) --> `deny`
- [template](https://github.com/ivankorn/terraform-google-org-policy/blob/7/test/integration/list_constraints/launch.sh#L145) --> [check](https://github.com/ivankorn/terraform-google-org-policy/blob/7/test/integration/list_constraints/integration.bats#L96) --> `allow`

As well as there are tests for `boolean constraints`:
- [template](https://github.com/ivankorn/terraform-google-org-policy/blob/7/test/integration/boolean_constraints/launch.sh#L96) --> [check](https://github.com/ivankorn/terraform-google-org-policy/blob/7/test/integration/boolean_constraints/integration.bats#L55)

Since all of the integration tests are [passing](https://github.com/terraform-google-modules/terraform-google-org-policy/pull/11#issuecomment-514211801) I'm assuming the behavior you mentioned is preserved.

There are also 2 boolean and 3 list [examples](https://github.com/ivankorn/terraform-google-org-policy/tree/7/examples) which are all [passing](https://github.com/terraform-google-modules/terraform-google-org-policy/pull/11#issuecomment-514211801)

Does it work as confirmation?
There might be some `not covered` cases, as the one @bohdanyurov-gl and I highlighted in this issue. Which, however seems to be fixed(to be tested) as a bonus on top of migration to tf 0.12

**Comment by morgante** [comment]
Thanks for confirming, we will check to make sure as part of the review process.

**Comment by aaron-lane** [comment]
I think we may have made a mistake in #13, specifically here: https://github.com/terraform-google-modules/terraform-google-org-policy/pull/11/files#diff-7a370d8342e7203b805911c92454f0f4R30. `local.invalid_config_case_2` checks the value of `var.enforce` rather than `local.enforce`, and the latter is no longer referenced.

**Comment by nick4fake** [comment]
![image](https://user-images.githubusercontent.com/1065993/67223383-d8d92980-f437-11e9-8d46-7a9d83c73271.png)
I've rechecked, it has been fixed. We can close this one.

**Comment by morgante** [comment]
@bohdanyurov-gl That looks like exactly the issue which @aaron-lane described (`local.enforce` isn't being referenced).

**Comment by nick4fake** [comment]
@morgante the case that @aaron-lane has mentioned is totally fine, as there is similar check in invalid_config_case_2 ( var.allow_list_length + var.deny_list_length > 0 )

**Comment by morgante** [comment]
@nick4fake Ok, the thing I want you to test is that boolean and list constraints will both be enforced by default if you *don't* specify the enforce variable.

**Comment by nick4fake** [comment]
@morgante, @aaron-lane 
I am fine with changing logic so that it is enforced by default, just wanted to emphasize:
1. @ivankorn review hasn't changed logic in any way. It is mapped 1 to 1 to the previous behavior
2. It is fine to have var.enforce in both boolean constraints and in the case that @aaron-lane has noted. It is not related to local.enforce (that is used for list constraints)

**Comment by nick4fake** [comment]
@morgante 
It is tricky to set var.enforce to "true" by default, because it is not compatible with list constraints. Three cases must be supported (based on both README and code):
- enforce is true - list policies are set to deny all
- enforce is false - list policies are set to allow all
- enforce is null - allow and deny lists start working

There is a confusion in README:
![image](https://user-images.githubusercontent.com/1065993/67330615-4ca53000-f525-11e9-99ef-8b9eb6d5de88.png)
This part doesn't make sense.

Anyway, I've updated var.enforce default to true + made small changes to README.
https://github.com/terraform-google-modules/terraform-google-org-policy/pull/24

**Comment by morgante** [comment]
@nick4fake Why doesn't it make sense? Yes, it takes some logic to implement (which is why we originally had more complicated logic using `local.enforce`), but there are a few possible scenarios:

1. You don't set enforce, allow, or deny => default is policy gets enforced
2. You explicitly set enforce.
3. You set an allow list (and cannot set enforce)
4. You set a deny list (and cannot set enforce)

Please make sure all 4 are supported.

**Comment by nick4fake** [comment]
@morgante then I can suggest the following changes:

var.enforce is null by default (to differ setting var.enforce to true from default true value for list constraints)

for bool constraints:
- default var.enforce value (null) means true
- var.enforce true/false logic is preserved

for list constraints:
- default var.enforce value (null) means true **if allow/deny lists are empty**
- default var.enforce value (null) is ignored  **if allow/deny lists are not empty**
- var.enforce true/false logic is preserved (error is thrown if allow/deny lists are not empty)

**Comment by morgante** [comment]
Yes, sounds correct.
