### ISSUE TITLE
Provide standard set of initial org policies

### ISSUE THREAD

**Issue by morgante** [terraform-google-modules/terraform-google-org-policy#15]
We should provide these out of the box:

- External IPs for VM instances
- Skip default network creation
- Domain restricted sharing (Beta)
- Enforce Bucket Policy Only

**Comment by averbuks** [comment]
Hi @morgante, how do you think the `initial set` should look like? 
1. As examples? 
2. As submodules calling main module? 
3. As optional functionality of the main module? Not sure that its' good idea

**Comment by morgante** [comment]
@averbuks I'm thinking as a submodule calling the main module would work well.
