### ISSUE TITLE
for_each/dynamic blocks rewrite

### ISSUE THREAD

**Issue by sleterrier** [terraform-google-modules/terraform-google-org-policy#16]
Hi,

I Just wanted to let you know that I re-wrote this module with for_each and dynamic blocks: https://github.com/sleterrier/terraform-google-org-policy
It allows for constraints to be added/removed without triggering a re-create of already existing resources. Most of the module behavior is however controlled from the input map, which might be a departure from this module philosophy.

Sorry for polluting your issues board with this, but I thought you might be interested in seeing another >=0.12.6 approach.

**Comment by morgante** [comment]
Very cool! Would you be willing to contribute a PR?

**Comment by sleterrier** [comment]
It makes for a pretty messy PR, but here you go: https://github.com/terraform-google-modules/terraform-google-org-policy/pull/23

**Comment by mandeep-bal** [comment]
hey @sleterrier how can i execute multiple constraints and keep the old state file preserved so that whenever i add a new constraint the older one doesnt get removed.
