### ISSUE TITLE
Version number not found for module

### ISSUE THREAD

**Issue by Nithesh-b** [terraform-google-modules/terraform-google-org-policy#40]
The version number is not mentioned in the README.md unlike other terraform google modules.

**Comment by bharathkkb** [comment]
@Nithesh-b thanks for the report! Would be happy to review a PR

**Comment by Nithesh-b** [comment]
Created the PR - https://github.com/terraform-google-modules/terraform-google-org-policy/pull/41

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-org-policy/pull/41
