### ISSUE TITLE
SUBMODULE for restricting public ip of sql

### ISSUE THREAD

**Issue by ankiclockwise** [terraform-google-modules/terraform-google-org-policy#46]
main.tf
module "org-policy-sql-restrict-public-ip" {
  source            = "../../"
  policy_for        = var.policy_for
  organization_id   = var.organization_id
  folder_id         = var.folder_id
  project_id        = var.project_id
  constraint        = "constraints/sql.restrictPublicIp"
  policy_type       = "list"
  exclude_folders   = var.exclude_folders
  exclude_projects  = var.exclude_projects
}

README EXAMPLE:

module "org-policy-sql-restrict-public-ip" {
  source            = "terraform-google-modules/org-policy/google"
  version           = "~> 3.0.2"
  constraint        = "constraints/sql.restrictPublicIp"
  policy_type       = "list"
  enforce           = true
  policy_for        = "folder"
  folder_id         = "folders/<folder id>"
}

**Comment by morgante** [comment]
What is your issue / question?
