### ISSUE TITLE
Domain Restricted Sharing README update

### ISSUE THREAD

**Issue by ankiclockwise** [terraform-google-modules/terraform-google-org-policy#47]
when i put the domain name there was a permission error. It'll be good to know through the readme that
**_you must have the roles/resourcemanager.organizationViewer role (or equivalent permissions) at the organization level_**

**Comment by bharathkkb** [comment]
We have the permissions listed here https://github.com/terraform-google-modules/terraform-google-org-policy#permissions
Feel free to reopen if that does not clarify.

**Comment by ankiclockwise** [comment]
The above link mentions organisation policy Admin role . But Domain-restricted-sharing module has **google_organisation** data source inside main.tf that needs the roles/resourcemanager.organizationViewer. right?

**Comment by ankiclockwise** [comment]
> We have the permissions listed here https://github.com/terraform-google-modules/terraform-google-org-policy#permissions
> Feel free to reopen if that does not clarify.

The above link mentions organisation policy Admin role . But Domain-restricted-sharing module has google_organisation data source inside main.tf that needs the roles/resourcemanager.organizationViewer. right?
