### ISSUE TITLE
Use Organization Policy API V2 instead of Cloud Resource Manager API V1

### ISSUE THREAD

**Issue by dmorellet** [terraform-google-modules/terraform-google-org-policy#51]
### TL;DR

Since [terraform-provider-google v3.87.0](https://github.com/hashicorp/terraform-provider-google/releases/tag/v3.87.0), there is a warning message in the google_organization_policy resource docs saying :
"The resource google_organization_policy has been superseded by google_org_policy_policy. It uses Organization Policy API V2 instead of Cloud Resource Manager API V1 and it supports additional features such as tags and conditions."

Could it be implemented in this module so we can effectively use the new tags and conditions features ?

### Terraform Resources

```markdown
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_organization_policy
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/org_policy_policy
```

**Comment by prabhu34** [comment]
I'm working on the submodule for supporting v2.

**Comment by bharathkkb** [comment]
fixed by https://github.com/terraform-google-modules/terraform-google-org-policy/pull/58. Thanks @prabhu34!
