### ISSUE TITLE
List type error

### ISSUE THREAD

**Issue by faizanseedat** [terraform-google-modules/terraform-google-org-policy#6]
Here is the main.tf module:

```
module "org-policy" {
  source               = "terraform-google-modules/org-policy/google"
  policy_type           = "list"
  constraint           = "constraints/serviceuser.services"
  organization_id   = "12345566"
  enforce               = "true"
}
```
Error: Invalid argument name
  on .terraform/modules/org-policy/terraform-google-modules-terraform-google-org-policy-8428ed4/main.tf line 53, in resource "null_resource" "config_check":
  53:   "For list constraints only one of enforce, allow, and deny may be included." = true
Argument names must not be quoted.

What does the constraint issue message mean? It is defined as true. I also tried to just input allow and deny, which resulted in the same error. 

What does this message mean? **Argument names must not be quoted**. From the examples derived, all parameters must be in quotes as defined by terraform code.

**Comment by aaron-lane** [comment]
Hi @faizanseedat. I apologize for the frustrating experience. What you are seeing is the result of a [hack to provide custom error messages within Terraform](https://github.com/terraform-google-modules/terraform-google-org-policy/blob/master/main.tf#L37-L52). However, it doesn't appear that your configuration is triggering any of the [invalid cases](https://github.com/terraform-google-modules/terraform-google-org-policy/blob/master/main.tf#L29-L31). Can you confirm if the shared configuration is complete, and which version of Terraform you are using?

**Comment by faizanseedat** [comment]
Hi @aaron-lane,
It seems that these issues are because of the code running sole on terraform version 11 and not terraform 12. Users have to downgrade to version 11 to ensure that this code is running per github.

Thanks,
Faizan

**Comment by aaron-lane** [comment]
That is correct, this module does not yet support Terraform v0.12.
